### ISSUE TITLE
[Feature] Export optimized cuda graph

### ISSUE THREAD

**Issue by digital-nomad-cheng** [hidet-org/hidet#130]
Is there a way to export the optimized cuda graph to runtime library/cuda kernel and call the runtime library from host?
If there is, which APIs should I check to do this?

**Comment by yaoyaoding** [comment]
Hi @digital-nomad-cheng,

Hidet supports dump and load a model (in the form of a [FlowGraph](https://docs.hidet.org/stable/python_api/graph/index.html#hidet.graph.FlowGraph) via its save and load method). The dumpped model will store all the information (e.g., model structure, weights) but will  leave the compiled kernels to hidet [cache](https://docs.hidet.org/stable/notes/operator-cache.html#). 

Currently, Hidet only has a Python-based runtime to execute a flow graph. We are still working on a VM-based runtime (e.g., TVM and Raf has such a [VM runtime](https://github.com/apache/tvm/tree/main/src/relay/backend/vm)). In the future, we will have a VM-based runtime that executes a hidet compiled model without Python enviroment, but now we still need python to run the model.

Let me know if you have any other question about Hidet.

**Comment by digital-nomad-cheng** [comment]
> 

Thanks for clarification, looking forward to the VM-based runtime.
