### ISSUE TITLE
[Bug]  Performance regression of softmax following PR #122

### ISSUE THREAD

**Issue by xinli-git** [hidet-org/hidet#133]
**Describe the bug**
There is a performance regression for the softmax operator following the change with PR #122 
**To Reproduce**
```bash
git checkout 3869540f33ede74a22922f33721e0b66699c5412
```
Run the following script with `pytest`
```python
import pytest
import numpy as np

import hidet as hi
from hidet import ops

from hidet.testing import check_unary

import git
repo = git.Repo(search_parent_directories=True)
sha = repo.head.object.hexsha
print(sha)
hi.option.cache_dir('./cache_{}'.format(sha))


def numpy_softmax(data, axis):
    data = np.exp(data - np.max(data, axis, keepdims=True))
    data = data / np.sum(data, axis, keepdims=True)
    return data


@pytest.mark.parametrize(
    "shape, axis",
    [[[16, 1024, 1024], 2],] 
)
def test_softmax(shape, axis):
    check_unary(
        shape, lambda x: numpy_softmax(x, axis), lambda x: ops.softmax(x, axis), dtype='float16', atol=1, rtol=1, device='cuda',
    )

```
```bash
git checkout HEAD^ # previous commit
```
Run the script again with `pytest`

Diff the generated kernel code
```bash
diff -r cache_3869540f33ede74a22922f33721e0b66699c5412 cache_e57b798a427fbfb13c386f0ae34839a909fbfb7a
```
There is a big increase in index calculation and redundant checks. This is possibly introduced by the changes in TaskMapping but I was not able to locate exactly where.

**Expected behavior**
Performance should be similar, kernel code should not introduce too much index calculation and if statements

**Enviroment**
 - OS: [ Ubuntu 22.04]
 - GPU: [RTX 3090]
 - Others: [e.g. NVIDIA GPU 520.61.05]

**Additional context**

**Comment by yaoyaoding** [comment]
Hi @xinli-git,

I have filed an PR to fix this bug. The root of this bug is that during refactring IR functors, I only analyzed all the expressions, but not the hidet.ir.Function in the rule based simplifier. This prevents hidet to track the bound info for external variables like threadIdx and blockIdx.

**Comment by xinli-git** [comment]
Thank you @yaoyaoding ! Will close tis after PR is merged :)
