### ISSUE TITLE
[Bug] pip install fails, Cannot open include file: 'nvtx3/nvToolsExt.h': No such file or directory ; CUDA Toolkit installed, works in VS19

### ISSUE THREAD

**Issue by trancenoid** [hidet-org/hidet#191]
**Describe the bug**
Platform : Windows 10
pip install fails at stage "Building wheel for nvtx" with error `Cannot open include file: 'nvtx3/nvToolsExt.h': No such file or directory`
Cuda toolkit 12.1 is installed. Importing the module in VS19 works (starting a project with CUDA Toolkit).

**To Reproduce**
`pip install hidet`

**Expected behavior**
installation should succeed

**Enviroment**
 - OS: Windows 10
 - GPU: GTX 1660Ti
 - Others: CUDA Toolkit 12.1.1

**Additional context**
Installing in conda environment

**Comment by yaoyaoding** [comment]
Hi @trancenoid,

We have not supported Windows yet. Currently, our focus is still on Linux system.
