### ISSUE TITLE
Comparison against TensorRT, was it in FP32 or FP16?

### ISSUE THREAD

**Issue by kshitizgupta21** [hidet-org/hidet#199]
In the [Hidet paper](https://arxiv.org/pdf/2210.09603.pdf), comparison against TensorRT 
<img width="263" alt="image" src="https://user-images.githubusercontent.com/73861554/235196186-46373302-06f6-421c-a365-5c95fb35b662.png">

was this in FP32 or FP16?

**Comment by yaoyaoding** [comment]
Hi @kshitizgupta21, all numbers in Hidet paper are for float32 data type. 

We did a lot of work since the paper submission, and now, hidet supports float16 and tensor core.
