### ISSUE TITLE
[Feature] Does hidet support dynamic shape compilation? 

### ISSUE THREAD

**Issue by tiandiao123** [hidet-org/hidet#211]
hey friends: I am wondering whether hidet supports dynamic shape compilation? I didn't see something related to dynamic shape discussion in the original paper: https://dl.acm.org/doi/pdf/10.1145/3575693.3575702

**Comment by yaoyaoding** [comment]
Hi @tiandiao123,

The original paper and hidet artifact in the paper do not support dynamic shape. We are currently adding the support for dynamic shape, and have already made good progress. Please stay tuned for the support!

See also #198.

**Comment by tiandiao123** [comment]
> Hi @tiandiao123,
> 
> The original paper and hidet artifact in the paper do not support dynamic shape. We are currently adding the support for dynamic shape, and have already made good progress. Please stay tuned for the support!
> 
> See also #198.

Thanks! @yaoyaoding
