### ISSUE TITLE
[Feature] Support torch.min and torch.max

### ISSUE THREAD

**Issue by eric8607242** [hidet-org/hidet#215]
Hi, thanks for the great work.

I would appreciate it if hidet could support [torch.min](https://pytorch.org/docs/stable/generated/torch.min.html) and [torch.max](https://pytorch.org/docs/stable/generated/torch.max.html).
This is very helpful in my case.

Thanks!

**Comment by yaoyaoding** [comment]
Hi @eric8607242,

Added in #216.

**Comment by eric8607242** [comment]
Hi, @yaoyaoding,

Thanks for the quick support!
Close the issue
