### ISSUE TITLE
Question: how does hidet perform graph-level transformation? and combined with other optimisation, e.g. rule-based scheduling?

### ISSUE THREAD

**Issue by hgl71964** [hidet-org/hidet#218]
Hi,

Is there an example to illustrate graph-level pattern matching transformation, and combined that with subgraph level scheduling?

Thanks

**Comment by yaoyaoding** [comment]
Hi @hgl71964,

You can learn more about the graph-level pattern matching-based transformation at: https://docs.hidet.org/stable/gallery/how-to-guides/add-subgraph-rewrite-rule.html

The corresponding pass is implemented at: 
https://github.com/hidet-org/hidet/blob/main/python/hidet/graph/transforms/subgraph_rewrite.py

The sub-graph level scheduling (or post-scheduling fusion in the paper) is implemented at:
https://github.com/hidet-org/hidet/tree/main/python/hidet/graph/ops/definitions/fusion

I would suggest you set the cache directory first to your current working directory (see https://docs.hidet.org/stable/notes/operator-cache.html) and turn on the option to save the IR during optimization and lowering (see https://docs.hidet.org/stable/python_api/option.html#hidet.option.save_lower_ir and https://docs.hidet.org/stable/python_api/option.html#hidet.option.save_lower_ir) to checkout the input and output of these passes.

You can run the following example
```python
import hidet

# change the cache directory
hidet.option.cache_dir('./outs/cache')

# save the tensor program level ir in operator cache
hidet.option.save_lower_ir()


def main():
    # construct a simple graph
    x = hidet.symbol([1, 3, 224, 224], device='cuda')
    w = hidet.randn([64, 3, 7, 7], device='cuda')
    x = hidet.ops.pad(x, [3, 3, 3, 3])
    x = hidet.ops.conv2d(x, w, stride=2)
    x = hidet.ops.relu(x)
    graph = hidet.trace_from(x)
    print(graph)

    # graph optimizations
    with hidet.graph.PassContext() as ctx:
        # save the computation graph level ir
        ctx.save_graph_instrument(out_dir='./outs/graphs')
        graph_opt = hidet.graph.optimize(graph)

    # run the optimized graph
    xx = hidet.randn([1, 3, 224, 224], device='cuda')
    yy = graph_opt(xx)


if __name__ == '__main__':
    main()
```
You will find a directory named `./outs` and it contains the operators (see https://docs.hidet.org/stable/notes/operator-cache.html) and intermediate graphs (see https://docs.hidet.org/stable/gallery/how-to-guides/visualize-flow-graph.html to learn how to visualize them).

**Comment by yaoyaoding** [comment]
It would be helpful if you dig into the hidet's compilation process using python debugger.

**Comment by hgl71964** [comment]
Thanks! that looks helpful!
