### ISSUE TITLE
[Feature] Is it any way to estimate the model compilation or remaining time?

### ISSUE THREAD

**Issue by ke1ne** [hidet-org/hidet#231]
The model compilation process is pretty long. As a user, I would have at least a rough idea about the time remaining. Is it possible?
Thanks!

**Comment by yaoyaoding** [comment]
Hi @ke1ne, thanks for bringing this up. Currently, it would be hard to add an estimate time as we do not know how many sub-graphs will be dispatched to hidet from pytorch. We will working on reducing the tuning time, though, and hope this would be a problem in the future.
