### ISSUE TITLE
Is there any way for users to inspect the connections between cuda kernels compiled from operators?

### ISSUE THREAD

**Issue by VincentXWD** [hidet-org/hidet#385]
I would like to see the connections between all cuda kernels generated by hidet in .cache folder. It seems that the directory is organized by operator categories without any other information about the connection only contains operator named directory and hash-named operator cuda kernel instances.

I wonder if I could get enough information(some config or some in-code position to add some prints to help me get the map of hash-named kernels and operators) so that I can construct some NN by myself using these kernels.

**Comment by VincentXWD** [comment]
Thank you for your replying and the reference .py code. Yes this is the way to get the task-operator mapping but I still cannot decide the positions of compiled kernels in network.

I wonder know if I can get the connections of these kernels.

For example, suppose I have some tasks:
```
dde7be8d40f119f8 : fused(y=float32(2304,), x=float32(1, 40, 2304), y=float32(3, 12, 40, 64), fused_ops='reshape add reshape rearrange', anchor='rearrange')

4742a24e5f0cf34e : fused(b=float32(8, 96, 2304), data=float32(40, 768), y=float32(1, 8, 40, 2304), fused_ops='broadcast reshape rearrange batch_matmul reshape', anchor='batch_matmul')

8315bfe1649dc27f : fused(b=float32(1, 768, 50257), data=float32(40, 768), y=float32(40, 50257), fused_ops='broadcast batch_matmul reshape', anchor='batch_matmul')

003b329f9684cc83 : fused(b=float32(8, 96, 3072), data=float32(40, 768), y=float32(1, 8, 40, 3072), fused_ops='broadcast reshape rearrange batch_matmul reshape', anchor='batch_matmul')

69b07ec79b8aaf99 : fused(y=float32(40, 40), x=float32(12, 40, 40), y=float32(96, 40, 5), fused_ops='reshape divs add softmax rearrange reshape rearrange', anchor='softmax')

289abe506ef9afa1 : fused(y=float32(40, 768), x=float32(40, 768), x=float32(1, 40, 768), z=float32(40, 768), fused_ops='reshape add add', anchor='add')

```

I would like to get a DAG-like description so that I can construct the network using these generated kernels:

```
dde7be8d40f119f8 -> 4742a24e5f0cf34e
         |                  L---------------------------|
         v                                              v
003b329f9684cc83 -> 69b07ec79b8aaf99 -> 289abe506ef9afa1 -> 8315bfe1649dc27f

```

**Comment by yaoyaoding** [comment]
Hi @VincentXWD,

I see. You can dump the compiled model like https://github.com/hidet-org/hidet/blob/main/tests/unit_tests/test_compiled_model.py to a single file. After you run the demo code, you will get a `model.hidet` file, which is a zip file and you can open it directly with zip file brower. 

It looks like 
![image](https://github.com/hidet-org/hidet/assets/23381083/ce06ac91-6dfa-4a62-a586-8a8b6cf39062)

All the kernels are stored in `/kernels` directory. The `graph_string.txt` stores the textual representation of the model while you can check the `graph_execution.json` to know the relationship between the operators and compiled kernels (the `task_idx` in each `instructions` entry). 

See https://github.com/hidet-org/hidet/blob/main/python/hidet/runtime/compiled_graph.py#L437 to know how we load and run the model stored in `model.hidet`.

**Comment by yaoyaoding** [comment]
When you load a `model.hidet`, we will also extract all the contents (except `weights.npz`) to hidet's cache directory. 

If you are using pytorch frontend, you might not be able to get the compiled model dumped to the disk. (We can add an option to support this functionality though)

**Comment by VincentXWD** [comment]
Thanks @yaoyaoding. I found the cache/graphs/ directory and learned about the file `graph_execution.json`. It described all information that I want.

It seems that hidet finishes the load process in python frontend. Actually I want to try something using another heterogeneous computing framework to optimize the inference process of networks. So the weights is quite important for me, too. It's great if you could provide a dump method to save these parameters to disks. But I think I can dump it by myself at present.

Hidet is such a great project with clear architecture and high performance, also many instructions for users to reachout the intermediate data. And it's really a good choice to be one of a compiler backend of pytorch.

Digress from the topic at hand, do you have any intentions to build your own runtime library for users not only as a backend for pytorch? :-D

**Comment by yaoyaoding** [comment]
If you want to dump the weights to disk, you can add the relative logic to this function https://github.com/hidet-org/hidet/blob/main/python/hidet/drivers/build_graph.py#L285
