### ISSUE TITLE
[FEATURE] Meet an undefined operator when compiling NASNet

### ISSUE THREAD

**Issue by VincentXWD** [hidet-org/hidet#398]
hello, I'm using hidet to compile PNASNET-5-LARGE defined here https://github.com/Cadene/pretrained-models.pytorch#pnasnet

And I met an undefined operator 'torch.nn.ZeroPad2d':

NotImplementedError: The following modules/functions are not supported by hidet yet:
  torch.nn.ZeroPad2d

Could someone please add this module into hidet? thanks.

**Comment by yaoyaoding** [comment]
Hi @VincentXWD,

I have added the missing operators in #399, could you check whether it works?

**Comment by VincentXWD** [comment]
Thank you @yaoyaoding, I'll check it later.

Happy holidays.

**Comment by VincentXWD** [comment]
@yaoyaoding  Thanks, it works. Good job!
