### ISSUE TITLE
[Bug]  How do you handle graph breaks coming from Dynamo?

### ISSUE THREAD

**Issue by tbaggu** [hidet-org/hidet#431]
Hi

I am taking this repo as reference to implement code for our custom back-end. During the development process most of the cases when i use hugging-face models directly i see lot of graph breaks, in Fx graph, 

My understanding on the inductor side is, each subgraph compiled and ran the inference sent the results to CPU, and the next subgraph will start executing which is time consuming?

So my question is , 
Have you seen such graph breaks if so how Hidet handles them?

similar to below case 
https://discuss.pytorch.org/t/stitching-together-graph-breaks-for-large-compilation-units/194793/5

**Comment by yaoyaoding** [comment]
Hi @tbaggu ,

The dynamo custom backends can not control how the torch model is partitioned and converted to fx graph. 

The torch dynamo dispatch the fx graph to custom backend and the backend compiles the fx graph to some executable and returns to dynamo. The compilation only happens once and the compiled executable will be used many times. As long as the compiled executable is efficient, the overhead will not be very large.

**Comment by tbaggu** [comment]
Hi

Thanks for the quick response, Is it each sub graph compiled and executed then the second will compile ??

 Is that flow is n sequence?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tbaggu** [comment]
So for each  subgraph  result should comeback to CPU and again it goes back to device right? Which is latency over head right?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by yaoyaoding** [comment]
> for each  subgraph  result should comeback to CPU

No, the result will stay in the same device (cpu or gpu) as the eager execution of the orginal model.

**Comment by wangshangsam** [comment]
Closing as this issue is not directly related to Hidet.
