### ISSUE TITLE
Google Colab: KeyError Primitive function cuda_i64_to_f16 has already registered

### ISSUE THREAD

**Issue by egorsmkv** [hidet-org/hidet#444]
**Describe the bug**

I am trying to install hidet 0.3.1 on Google Colab

**To Reproduce**

```
pip install https://github.com/hidet-org/hidet/archive/refs/tags/v0.3.1.zip
```

```
import hidet

print('hidet:', hidet.__version__)
```

**Expected behavior**

To see the hidet version

**Additional context**

Instead of the hidet version I am getting this error:

<img width="1154" alt="image" src="https://github.com/hidet-org/hidet/assets/7875085/6944e960-4db2-418a-8d12-a5fcd9de0d07">

**Comment by vadiklyutiy** [comment]
Egor, 

with hidet==0.5.0

Test passed successfully. 
``` bash
$ pip show hidet
Name: hidet
Version: 0.5.0
Summary: Hidet: a compilation-based DNN inference framework.
Home-page: https://docs.hidet.org
Author:
Author-email:
License: Apache-2.0
Location: /tmp/venv/lib/python3.10/site-packages
Requires: astunparse, click, cuda-python, filelock, lark, numpy, nvtx, packaging, psutil, pytest, requests, scipy, tabulate, tomlkit, tqdm
Required-by:

$ cat tmp.py
import hidet
print('hidet:', hidet.__version__)

$ python tmp.py
hidet: 0.5.0

```

If you still has same issue in your env please feel free to reopen.
