### ISSUE TITLE
[Bug] Need to port Publish to PyPl workflow to ARC cluster

### ISSUE THREAD

**Issue by vadiklyutiy** [hidet-org/hidet#457]
After merging from CentML/hidet Tests workflow runs on ARC cluster. But there is one more workflow that counts on the previously used instance - "Publish to PyPl" workflow. 
We need to port it to running on ARC cluster. 

@yaoyaoding @wangshangsam @c-fteixeira

**Comment by yaoyaoding** [comment]
In the `Publish to PyPI` workflow, there are two steps:
1. Perform release-level tests
2. Build the package wheel and submit to PyPI

The first step requires a GPU while the second step does not. It's okay to only port for the first step to run on the arc cluster. @c-fteixeira

**Comment by vadiklyutiy** [comment]
maybe instead of 1. we can just call Test workflow?

For 2. do we need GPU for this actions?

**Comment by yaoyaoding** [comment]
> if so, we can instead of 1. just call Test workflow. Publish workflow move to GitHub hosted server. @yaoyaoding Is it correct that Publish use the same tests set as Test?

The current release tests are the same as our daily tests. But we planned to enable some slow tests in the release tests.

**Comment by vadiklyutiy** [comment]
> The current release tests are the same as our daily tests. But we planned to enable some slow tests in the release tests.

I think it might be just a arg of workflow that enables slow tests. No need to copy-paste a lot

**Comment by yaoyaoding** [comment]
Yeah, it's better if we can resue some workflow code by using arg to specify whether to enable more tests.

**Comment by vadiklyutiy** [comment]
@c-fteixeira is it done? yes?

**Comment by c-fteixeira** [comment]
closed by #461  and #463
