### ISSUE TITLE
[CI] Test Publish on wheel or not 

### ISSUE THREAD

**Issue by vadiklyutiy** [hidet-org/hidet#462]
I merged #461 to be able release the version. But there is unresolved discussion. 

I think we should use the wheel package for final testing, not a clone of repo. If there are any issues in the wheel we didn't check it. 

 @wangshangsam @yaoyaoding

**Comment by yaoyaoding** [comment]
> I merged #461 to be able release the version. But there is unresolved discussion.
> 
> I think we should use the wheel package for final testing, not a clone of repo. If there are any issues in the wheel we didn't check it.
> 
> @wangshangsam @yaoyaoding

I think so, it's better to
1. build the release wheel with `scripts/wheel/build_wheel_manylinux1.sh`.
2. run the test using the built wheel that we are going to release.

**Comment by wangshangsam** [comment]
> I think we should use the wheel package for final testing, not a clone of repo.

+1

**Comment by vadiklyutiy** [comment]
We immediately got proof of this claim :)

**Comment by vadiklyutiy** [comment]
similar to https://github.com/CentML/hidet/issues/384

**Comment by vadiklyutiy** [comment]
Right now Tests workflow use wheel for testing
