### ISSUE TITLE
Half function undefined during compilation

### ISSUE THREAD

**Issue by soodoshll** [hidet-org/hidet#81]
Try to run softmax with fp16, but get the error message ``error: identifier "__hmax" is undefined``.

It seems some functions don't exist on older hardware before Ampere. Please refer to [this](https://github.com/NVIDIA/TensorRT/issues/1003)

**Comment by yaoyaoding** [comment]
Hi @soodoshll, thanks for reporting this.

I have looked at the <cuda_fp16.h> header and found the following code snippet:
```c
#if !defined(__CUDA_ARCH__) || (__CUDA_ARCH__ >= 800)
...
__CUDA_FP16_DECL__ __half __hmax(const __half a, const __half b);
...
#endif
```
The [documentation](https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH____HALF__COMPARISON.html#group__CUDA__MATH____HALF__COMPARISON_1gcf7b00800f33f1e59780871fe31ff282) did not mention that this function only support SM>=8.0 (i.e., Ampere architecture).

Will fall back to something like `(half)max((float)a, (float)b)` later and let you know.
