### ISSUE TITLE
Perf numbers comparing against torch inductor and blade disc?

### ISSUE THREAD

**Issue by Jokeren** [hidet-org/hidet#82]
Just curious about the perf comparison between this work and others that also adopt the `compile` interface to optimize the computation graph. 

See https://github.com/alibaba/BladeDISC/releases/tag/v0.3.0

**Comment by yaoyaoding** [comment]
Hi @Jokeren, thanks for your interst in Hidet.

Currently, we only have comparison between PyTorch official dynamo backends (there are some errors when using inductor backend, thus in this benchmark we omitted it):
![image](https://user-images.githubusercontent.com/23381083/216778291-3c46b1cc-4294-4976-b6e3-b066b234c7a0.png)

We will have benchmakr on more models and backends after the PyTorch 2.0 official release.

**Comment by Jokeren** [comment]
Thanks. Looking forward to the up-to-date perf numbers
