### ISSUE TITLE
Does hidet have inputs with dynamic shapes support now?

### ISSUE THREAD

**Issue by changcui** [hidet-org/hidet#83]

**Comment by yaoyaoding** [comment]
Hi @changcui, sorry, we do not support dynamic shape for now. The support for dynamic shape is on the plan with high priority. 

The Hidet Script has the ability to write kernel with dynamic shape, see the [example](https://docs.hidet.org/stable/gallery/developer-guides/hidet-script-dynamic-kernel.html). However, to support the model with dynamic input (i.e., sequence length in text-generation models), we still need to enhance our graph IR and scheduling system.

**Comment by changcui** [comment]
Thanks for your reply. I will keep an eye on your work.
