### ISSUE TITLE
[Bug] broadcast_shape parameter type error

### ISSUE THREAD

**Issue by soodoshll** [hidet-org/hidet#85]
Hi!

I encounter this problem when I tried to optimize a onnx model. In

https://github.com/hidet-org/hidet/blob/0cd78c7828232062992d9d5429fd5b0179bf2daa/python/hidet/graph/frontend/onnx/onnx.py#L645

``data.shape`` is a Tuple. And in the definition of ``broadcast_shape``.

https://github.com/hidet-org/hidet/blob/0cd78c7828232062992d9d5429fd5b0179bf2daa/python/hidet/graph/ops/definitions/utils.py#L142

``x_shape`` will be a Tuple. However, ``[1] + x_shape`` will raise an error ``TypeError: can only concatenate list (not "tuple") to list``.

**Comment by yaoyaoding** [comment]
Hi @soodoshll, could you try again with the current main branch?
